#! /bin/bash


#THIS IS A GAG - DOES NOTHING BUT YOU CAN MAKE SB BELIEVE HIS COMPUTER IS INFECTED WITH A VIRUS

NAME=$(whoami)

zenity --warning --title="VIRUS" --text="HALLO ${NAME^^} DAS IST EIN VIRUS - IHR COMPUTER WURDE GEHACKT" --no-wrap
